[env:esp32-s3-dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DLOG_LOCAL_LEVEL=3
    -DI2S_BCK_PIN=5
    -DI2S_WS_PIN=6
    -DI2S_DO_PIN=7
    -DMIC_WS_PIN=8
    -DMIC_SD_PIN=9
    -DMIC_BCK_PIN=10
    -DONE_WIRE_PIN=11
    -DLED_PIN=48

lib_deps = 
    https://github.com/sle118/squeezelite-esp32.git
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit DS18X20
    knolleary/PubSubClient
